DATA:
  DATASET: 'custom'
  DATA_PATH: 'D:\Documents\Swin-Transformer\dataset'
  IMG_SIZE: 256
  BATCH_SIZE: 2
  NUM_WORKERS: 0
  PIN_MEMORY: True

MODEL:
  TYPE: 'swinv2'
  NAME: 'debug_swinv2_fusion'
  NUM_CLASSES: 3
  DROP_PATH_RATE: 0.1

  SWINV2:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 8

    #
    USE_ESC: True
    ESC_PDIM: 16
    ESC_KERNEL_SIZE: 13
    # ===================

  # ===
  FUSION:
    ENABLED: False
    CLINICAL_DIM: 4

    CSV_PATH: 'D:\Documents\Swin-Transformer\dataset\clinical_data.csv'
  # ===============================

TRAIN:
  EPOCHS: 1
  WARMUP_EPOCHS: 0
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  OPTIMIZER:
    NAME: 'adamw'


AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
  MIXUP_PROB: 0.0
  CUTMIX_MINMAX: null
# ===============================