DATA:
  DATASET: 'custom'
  DATA_PATH: 'dataset'
  IMG_SIZE: 256
  BATCH_SIZE: 32
  MEAN: [ 0.12020841240882874, 0.12020841240882874, 0.12020841240882874 ]
  STD: [ 0.12266180664300919, 0.12266180664300919, 0.12266180664300919 ]

MODEL:
  TYPE: 'swinv2'
  NAME: 'exp1_baseline'
  NUM_CLASSES: 3
  SWINV2:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 8
    USE_ESC: False
  FUSION:
    ENABLED: False

TRAIN:
  EPOCHS: 300
  BASE_LR: 1.25e-5
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  TARGET_ACC: 0.67
  EARLY_STOPPING:
    ENABLED: False
    PATIENCE: 30

AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
  COLOR_JITTER: 0.0
  AUTO_AUGMENT: 'none'