DATA:
  DATA_PATH: 'D:\Documents\Data\K\1'
  IMG_SIZE: 256
  BATCH_SIZE: 64
  MEAN: [ 0.12020841240882874, 0.12020841240882874, 0.12020841240882874 ]
  STD: [ 0.12266180664300919, 0.12266180664300919, 0.12266180664300919 ]
  INTERPOLATION: 'lanczos'

MODEL:
  TYPE: 'swinv2'
  NAME: 'exp4_full_model'
  RESUME: 'output/exp4_full_model/checkpoint_best.pth'
  NUM_CLASSES: 3

  SWINV2:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 8

    USE_ESC: True
    ESC_PDIM: 16
    ESC_KERNEL_SIZE: 13

  FUSION:
    ENABLED: True
    CLINICAL_DIM: 4
    CSV_PATH: 'dataset/clinical_data.csv'

TRAIN:
  EPOCHS: 500
  BASE_LR: 1.125e-5
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  TARGET_ACC: 0.83
  MIDDLE_ACC: 0.73
  EARLY_STOPPING:
    ENABLED: False
    PATIENCE: 30

AUG:
  MIXUP: 0.0
  CUTMIX: 0.0

OUTPUT: 'D:\Documents\Swin-Transformer\K_for_5\output\fold_1'